# Generated by Django 4.2.5 on 2023-10-30 03:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
    ]
