# Generated by Django 4.2.5 on 2023-11-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("userauth", "0003_delete_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("url", models.URLField()),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "target_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("check_frequency", models.IntegerField(default=10)),
                ("last_check_time", models.DateTimeField(auto_now_add=True)),
                ("enable_auto_monitoring", models.BooleanField(default=False)),
            ],
        ),
    ]
