# Generated by Django 4.2.5 on 2023-11-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0005_tracklist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracklist",
            name="timer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
