# Generated by Django 4.2.5 on 2023-11-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0006_tracklist_timer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracklist",
            name="timer_id",
            field=models.CharField(
                blank=True, default=False, max_length=255, null=True
            ),
        ),
    ]
